/* eslint-disable */
require('./add')
require('./clear')
require('./close')
require('./Collection')
require('./delete')
require('./file')
require('./filter-1')
require('./filter-9')
require('./filter')
require('./folder-open')
require('./icon-search')
require('./intersection')
require('./minimize')
require('./selectall')
require('./sort')
require('./tags')
require('./union')
